-- CREATE DATABASE chat;

USE chat;

DROP TABLE IF EXISTS `messages`;

CREATE TABLE `messages` (
  `id` INT(8) NULL AUTO_INCREMENT DEFAULT NULL,
  `username` CHAR(32) NULL DEFAULT NULL,
  `message` VARCHAR(256) NULL DEFAULT NULL,
  `room` CHAR(32) NULL DEFAULT NULL,
  `userid` INT(8) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);
